package br.ucsal.util;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class LoadTables {

	public void creatScherma(Connection c) throws SQLException {

		Statement stmt = c.createStatement();

		stmt.execute("CREATE TABLE ESPACOS ( ID INTEGER IDENTITY PRIMARY KEY,  IDENTIFICACAO VARCHAR(255),"
				+ " ANDAR  VARCHAR(255), FUNCAO VARCHAR(255), BLOCO_ID INTEGER, TIPO_ID INTEGER );");
		stmt.execute("CREATE TABLE USUARIOS (ID INTEGER IDENTITY PRIMARY KEY, NOME VARCHAR(255), "
				+ "LOGIN VARCHAR(255), SENHA VARCHAR(255)");
		stmt.execute("CREATE TABLE BLOCOS ( ID INTEGER IDENTITY PRIMARY KEY,  NOME VARCHAR(255),"
				+ " LETRA  VARCHAR(255), LATITUDE VARCHAR(255), LONGITUDE VARCHAR(255) );");
		stmt.execute("ALTER TABLE ESPACOS ADD FOREIGN KEY (BLOCO_ID) REFERENCES BLOCOS(ID);");
		stmt.execute(
				"CREATE TABLE TIPOS ( ID INTEGER IDENTITY PRIMARY KEY, NOME VARCHAR(255), DESCRICAO  VARCHAR(255));");
		stmt.execute("ALTER TABLE ESPACOS ADD FOREIGN KEY (TIPO_ID) REFERENCES TIPOS(ID);");

		stmt.execute(
				"CREATE TABLE RESERVAS ( ID INTEGER IDENTITY PRIMARY KEY, TITULO VARCHAR(255), DESCRICAO  VARCHAR(255), "
						+ "JUSTIFICATIVA VARCHAR(255), SOLICITANTE VARCHAR(255), TELEFONE VARCHAR(255), "
						+ "DATA DATE, HORAINICIO TIME, HORAFIM TIME, ESPACO_ID INTEGER);");
		stmt.execute("ALTER TABLE RESERVAS ADD FOREIGN KEY (ESPACO_ID) REFERENCES ESPACOS(ID);");

	}
}
